# Generated by Django 6.0.6 on 2026-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_rows', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('data_type', models.CharField(choices=[('current', 'Current'), ('forecast', 'Forecast'), ('historical', 'Historical')], db_index=True, max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'data_type', 'expires_at'], name='weather_wea_locatio_fcbaca_idx')],
                'unique_together': {('location', 'data_type')},
            },
        ),
    ]
